-- Sooru & Stories initial schema. Apply with Supabase CLI after reviewing policies.
create extension if not exists pgcrypto;
create type public.user_role as enum ('customer','admin');
create type public.order_status as enum ('pending_payment','payment_verification','paid','processing','ready_for_pickup','out_for_delivery','delivered','cancelled','failed','refund_pending','refunded');
create type public.payment_status as enum ('pending','authorized','captured','failed','refund_pending','refunded');
create table public.profiles (id uuid primary key references auth.users(id) on delete cascade, full_name text, phone text, role public.user_role not null default 'customer', created_at timestamptz not null default now(), updated_at timestamptz not null default now());
create table public.categories (id uuid primary key default gen_random_uuid(), name text not null unique, slug text not null unique, created_at timestamptz not null default now());
create table public.products (id uuid primary key default gen_random_uuid(), sku text unique, slug text not null unique, name text not null, description text not null default '', category_id uuid references public.categories(id), price_paise integer not null check(price_paise>=0), stock_quantity integer not null default 0 check(stock_quantity>=0), vegetarian boolean not null default false, published boolean not null default false, image_url text, created_at timestamptz not null default now(), updated_at timestamptz not null default now());
create table public.addresses (id uuid primary key default gen_random_uuid(), user_id uuid not null references auth.users(id) on delete cascade, recipient_name text not null, phone text not null, address_line1 text not null, address_line2 text, city text not null, state text not null, postal_code text not null, country_code char(2) not null default 'IN', created_at timestamptz not null default now());
create table public.carts (id uuid primary key default gen_random_uuid(), user_id uuid not null unique references auth.users(id) on delete cascade, updated_at timestamptz not null default now());
create table public.cart_items (id uuid primary key default gen_random_uuid(), cart_id uuid not null references public.carts(id) on delete cascade, product_id uuid not null references public.products(id), quantity integer not null check(quantity between 1 and 25), unique(cart_id,product_id));
create table public.orders (id uuid primary key default gen_random_uuid(), order_number text not null unique, user_id uuid references auth.users(id), customer_name text not null, customer_email text not null, customer_phone text not null, fulfilment_mode text not null check(fulfilment_mode in ('delivery','pickup','dine-in')), delivery_address jsonb, status public.order_status not null default 'pending_payment', payment_status public.payment_status not null default 'pending', currency char(3) not null default 'INR', subtotal_paise bigint not null check(subtotal_paise>=0), discount_paise bigint not null default 0 check(discount_paise>=0), tax_paise bigint not null default 0 check(tax_paise>=0), fulfilment_fee_paise bigint not null default 0 check(fulfilment_fee_paise>=0), total_paise bigint not null check(total_paise>=0), razorpay_order_id text unique, razorpay_payment_id text unique, attribution jsonb not null default '{}'::jsonb, idempotency_key text not null unique, created_at timestamptz not null default now(), updated_at timestamptz not null default now());
create table public.order_items (id uuid primary key default gen_random_uuid(), order_id uuid not null references public.orders(id) on delete cascade, product_id uuid references public.products(id), sku_snapshot text, name_snapshot text not null, unit_price_paise integer not null check(unit_price_paise>=0), quantity integer not null check(quantity between 1 and 25), line_total_paise bigint not null check(line_total_paise>=0));
create table public.payment_events (id uuid primary key default gen_random_uuid(), provider text not null, provider_event_id text not null, event_type text not null, order_id uuid references public.orders(id), payload_hash text not null, processed_at timestamptz, created_at timestamptz not null default now(), unique(provider,provider_event_id));
create table public.email_events (id uuid primary key default gen_random_uuid(), order_id uuid references public.orders(id), event_type text not null, idempotency_key text not null unique, provider_message_id text, status text not null default 'pending', last_error_code text, created_at timestamptz not null default now(), sent_at timestamptz);
create table public.order_status_history (id uuid primary key default gen_random_uuid(), order_id uuid not null references public.orders(id) on delete cascade, from_status public.order_status, to_status public.order_status not null, actor_user_id uuid references auth.users(id), note text, created_at timestamptz not null default now());
create table public.coupons (id uuid primary key default gen_random_uuid(), code text not null unique, discount_type text not null check(discount_type in ('fixed','percent')), discount_value integer not null check(discount_value>0), minimum_subtotal_paise bigint not null default 0, max_redemptions integer, redemption_count integer not null default 0, starts_at timestamptz, expires_at timestamptz, active boolean not null default false);
create index products_category_published_idx on public.products(category_id,published); create index orders_user_created_idx on public.orders(user_id,created_at desc); create index orders_status_created_idx on public.orders(status,created_at desc); create index order_items_order_idx on public.order_items(order_id);
alter table public.profiles enable row level security; alter table public.categories enable row level security; alter table public.products enable row level security; alter table public.addresses enable row level security; alter table public.carts enable row level security; alter table public.cart_items enable row level security; alter table public.orders enable row level security; alter table public.order_items enable row level security; alter table public.payment_events enable row level security; alter table public.email_events enable row level security; alter table public.order_status_history enable row level security; alter table public.coupons enable row level security;
create policy "published products are public" on public.products for select using (published=true);
create policy "categories are public" on public.categories for select using (true);
create policy "customers read own profile" on public.profiles for select to authenticated using (auth.uid()=id);
create policy "customers update own profile" on public.profiles for update to authenticated using (auth.uid()=id) with check (auth.uid()=id and role='customer');
create policy "customers manage own addresses" on public.addresses for all to authenticated using (auth.uid()=user_id) with check (auth.uid()=user_id);
create policy "customers manage own cart" on public.carts for all to authenticated using (auth.uid()=user_id) with check (auth.uid()=user_id);
create policy "customers manage cart items" on public.cart_items for all to authenticated using (exists(select 1 from public.carts c where c.id=cart_id and c.user_id=auth.uid())) with check (exists(select 1 from public.carts c where c.id=cart_id and c.user_id=auth.uid()));
create policy "customers read own orders" on public.orders for select to authenticated using (auth.uid()=user_id);
create policy "customers read own order items" on public.order_items for select to authenticated using (exists(select 1 from public.orders o where o.id=order_id and o.user_id=auth.uid()));
-- Payment, email, coupon and status-history tables have no customer policies: only trusted server code may access them. Admin access must be implemented with server-verified role checks; never grant admin by client-side profile update.
